# Kubernetes secrets for TAK Lite Server
# Apply this file after creating the secrets in your cluster

apiVersion: v1
kind: Secret
metadata:
  name: tak-lite-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  # Generate with: echo -n "your-secret" | base64
  
  # JWT Secret (generate a secure random string)
  JWT_SECRET: <base64-encoded-jwt-secret>
  
  # Database URL (if using external database)
  DATABASE_URL: <base64-encoded-database-url>
  
  # CORS Origin
  CORS_ORIGIN: <base64-encoded-cors-origin>
  
  # Redis Password (if using external Redis)
  REDIS_PASSWORD: <base64-encoded-redis-password>
  
  # RabbitMQ URL (if using external RabbitMQ)
  RABBITMQ_URL: <base64-encoded-rabbitmq-url>

---
# Example of how to create secrets using kubectl
# kubectl create secret generic tak-lite-secrets \
#   --from-literal=JWT_SECRET="your-secure-jwt-secret" \
#   --from-literal=DATABASE_URL="postgresql://user:pass@host:5432/db" \
#   --from-literal=CORS_ORIGIN="https://your-domain.com" \
#   --from-literal=REDIS_PASSWORD="your-redis-password" \
#   --from-literal=RABBITMQ_URL="amqp://user:pass@host:5672/"

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-lite-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  JWT_EXPIRES_IN: "7d"
